---
- hosts: Mainrouter
  connection: network_cli

  vars:
    ansible_network_os: routeros
    ansible_user: noc
    ansible_password: 123
  tasks:
    - name: Display resource statistics (routeros)
      routeros_command:
        commands: /system resource print
        

