---
- hosts: Mainrouter
  connection: network_cli

  vars:
    ansible_network_os: routeros
    ansible_user: noc

  tasks:
    - name: Display resource statistics (routeros)
      routeros_command:
        commands: ping count=10 8.8.8.8

