---
- hosts: Mainrouter
  connection: network_cli

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: community.network.routeros
    ansible_user: noc
    ansible_password: 123
    
  tasks:
  - name: Display resource statistics (routeros)
    community.network.routeros_command:
      commands: /system resource print
    register: routeros_resources
    
